### ISSUE TITLE
New logo for Kala

### ISSUE THREAD

**Issue by reallinfo** [bgroff/kala-app#10]
Hello, I wanted to contribute for Kala. I desgined logo for this. If you have any other ideas, do not hesitate to tell me.

![kala](https://user-images.githubusercontent.com/36298335/39050251-61391786-44ad-11e8-912a-a7d6f94c328d.jpg)

**Comment by bgroff** [comment]
Thank you! Two things, do you have a vector version of this? What license are you distributing this under?

**Comment by reallinfo** [comment]
Sure, I use[ Creativecommon](https://creativecommons.org/licenses/by/4.0/) license, you can use this logoy as you like. 

Here are all files.

https://drive.google.com/open?id=1Nw958QBHiQHe_TtfYc590-_byFaCOKL_

Do you want me to send you a pr? and I can update the Readme.

![1](https://user-images.githubusercontent.com/36298335/39064586-b4cc1a68-44d7-11e8-86d1-171011ebdf8c.jpg)

Which one do you prefer? and Do you have a color you want?
