### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by chrisingram22** [bgroff/kala-app#15]
Is there a simple way to translate it into Spanish?

**Comment by bgroff** [comment]
This is a great question and something I am hoping to get to soon. It would be nice to use a service like this: https://www.transifex.com/ but I need to add all the {% trans %} tags and gettext on all of the string in the Python code.

One more problem is that the application is still a bit of a moving target, so it is very possible that the strings will change somewhat frequently, which means that someone would need to keep the translations up to date. If you are interested in helping with a Spanish translation, I will try to get the infrastructure setup asap.

**Comment by chrisingram22** [comment]
I can help. What would I have to do specifically?

**Comment by bgroff** [comment]
I will set everything up with transifex and then you can just create an account there and fill in the translation strings. Hopefully I can get something setup today or tomorrow and provide more information.

**Comment by chrisingram22** [comment]
Sounds good!

**Comment by bgroff** [comment]
I have uploaded the .po file to the translation service. If you send me your email @ brycegroff@gmail.com I will send you an invite. Once you have a login you can go here:

https://www.transifex.com/kala/kala-app/translate/#es/djangopo/147484453

And fill out the es translations. If you see any doubles that are spelling mistakes or could be combined, let me know. Also everything inside {{ }} are template tags and the stuff inside needs to stay exactly how it is, but it can be moved around in the string as needed.

Also is general Spanish fine, or are you looking to translate for a particular dialect?

Thanks and I hope you find some time to do the translation! I will put your name in the README thanks section if you would like.

**Comment by bgroff** [comment]
Thank you! I will get get the translation in and some documentation added for how to use it in the next couple of days. I will also add you in the thank you section of the README.
