### ISSUE TITLE
Standalone Ubuntu Installation

### ISSUE THREAD

**Issue by WanderingCoder-Omen** [bgroff/kala-app#20]
Hi this looks really good. Awesome job!! I wanted to install this in a standalone Ubuntu VM on my laptop. How should I go about it ?

**Comment by bgroff** [comment]
You can read the documentation here: https://kala-app.readthedocs.io/en/latest/admin/manual/ubuntu.html it is for ubuntu 16.04, so the packages may have changed slightly. There are also vagrant scripts that may still work: https://github.com/bgroff/kala-app#development
