### ISSUE TITLE
Unable to create an empty server

### ISSUE THREAD

**Issue by fisadev** [bgroff/kala-app#4]
Following the steps from the readme, it fails on the syncdb after creating the admin user (which I have to, in order to have a user to login).

The error when creating the user is this:

```
IntegrityError: null value in column "company_id" violates not-null constraint
DETAIL:  Failing row contains (1, pbkdf2_sha256$10000$hr1hw7ycWFLY$H4rSOnaqQgkGKAZP6uFJJ52pAN2IxX+..., 2014-04-03 19:03:37.884562+00, f, admin, , , admin@admin.com, f, t, 2014-04-03 19:03:37.884562+00, null, null, Pacific/Honolulu, f, f, null, null, null, null, null, 2014-04-03 19:03:37.917581+00, null).
```

**Comment by bgroff** [comment]
The provision scripts now create a default project and organization and create the correct permissions for the two default users.
